In [16]:
import numpy as np
import pandas as pd

In [17]:
class StandardScaler:
    def __init__(self):
        self.mean=None
        self.std=None
    
    def fit(self,X_train):
        self.mean=X_train.mean(axis=0)
        self.std=X_train.std(axis=0)
        self.std[self.std==0]=1
        return self
    
    def fit_transform(self,X_train):
        self.fit(X_train)
        return (X_train-self.mean)/self.std
    
    def transform(self,X_test):
        return (X_test-self.mean)/self.std





In [18]:
class MinMaxScaler:
    def __init__(self,min=0,max=1):
        self.min=min
        self.max=max
        self.range=max-min
        self.min_val=None
        self.max_val=None
        if self.range<0:
            raise Exception("Min value is greater than max value")
        
    def fit(self,x):
        self.max_val=np.max(x,axis=0)
        self.min_val=np.min(x,axis=0)
        self.scale_=np.where(self.max_val-self.min_val==0,1,self.max_val-self.min_val)
        return self
    
    def fit_transform(self,x):
        self.fit(x)
        return self.min+(x-self.min_val)*(self.range)/self.scale_
    
    def transform(self,x):
        return self.min+(x-self.min_val)*(self.range)/self.scale_




# Testing StandardScaler


In [19]:
from sklearn.preprocessing import StandardScaler as SklearnScaler



# Sample data
X_train = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]], dtype=float)

X_test = np.array([[2, 3, 4],
                   [5, 6, 7]], dtype=float)

# Using custom scaler
custom_scaler = StandardScaler()
X_train_custom = custom_scaler.fit_transform(X_train)
X_test_custom = custom_scaler.transform(X_test)

# Using sklearn scaler
sklearn_scaler = SklearnScaler()
X_train_sklearn = sklearn_scaler.fit_transform(X_train)
X_test_sklearn = sklearn_scaler.transform(X_test)

# Compare results
print("Custom Scaler - Train:\n", X_train_custom)
print("Sklearn Scaler - Train:\n", X_train_sklearn)
print("\nCustom Scaler - Test:\n", X_test_custom)
print("Sklearn Scaler - Test:\n", X_test_sklearn)


Custom Scaler - Train:
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
Sklearn Scaler - Train:
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]

Custom Scaler - Test:
 [[-0.81649658 -0.81649658 -0.81649658]
 [ 0.40824829  0.40824829  0.40824829]]
Sklearn Scaler - Test:
 [[-0.81649658 -0.81649658 -0.81649658]
 [ 0.40824829  0.40824829  0.40824829]]


In [20]:
custom_scaler.mean

array([4., 5., 6.])

In [21]:
custom_scaler.std

array([2.44948974, 2.44948974, 2.44948974])

In [22]:
sklearn_scaler.mean_

array([4., 5., 6.])

In [23]:
sklearn_scaler.scale_

array([2.44948974, 2.44948974, 2.44948974])

In [24]:
sklearn_scaler.var_

array([6., 6., 6.])

# Testing MinMaxScaler

In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler as SklearnMinMaxScaler



# Sample data
X_train = np.array([[1, 2],
                    [3, 4],
                    [5, 6]], dtype=float)

X_test = np.array([[2, 3],
                   [4, 5]], dtype=float)

# Custom scaler
custom_scaler = MinMaxScaler(min=0, max=1)
X_train_custom = custom_scaler.fit_transform(X_train)
X_test_custom = custom_scaler.transform(X_test)

# Sklearn scaler
sklearn_scaler = SklearnMinMaxScaler(feature_range=(0, 1))
X_train_sklearn = sklearn_scaler.fit_transform(X_train)
X_test_sklearn = sklearn_scaler.transform(X_test)

# Compare results
print("Custom Scaler - Train:\n", X_train_custom)
print("Sklearn Scaler - Train:\n", X_train_sklearn)
print("\nCustom Scaler - Test:\n", X_test_custom)
print("Sklearn Scaler - Test:\n", X_test_sklearn)


print("\nTrain arrays equal:", np.allclose(X_train_custom, X_train_sklearn))
print("Test arrays equal:", np.allclose(X_test_custom, X_test_sklearn))


Custom Scaler - Train:
 [[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]
Sklearn Scaler - Train:
 [[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]

Custom Scaler - Test:
 [[0.25 0.25]
 [0.75 0.75]]
Sklearn Scaler - Test:
 [[0.25 0.25]
 [0.75 0.75]]

Train arrays equal: True
Test arrays equal: True
